"""ORIUS universal degraded-observation theory kernel."""

from .contracts import (
    ContractVerifier,
    ContractViolation,
    DomainInstantiation,
    ObservationConsistentStateSet,
    ObservationPacket,
    ReliabilityAssessment,
    RepairDecision,
    SafeActionSet,
    SafetyCertificate,
    SafetySpec,
    UniversalStepResult,
)
from .domain_runtime_contracts import (
    AV_BRAKE_HOLD_CONTRACT_ID,
    HEALTHCARE_FAIL_SAFE_CONTRACT_ID,
    DomainRuntimeContractWitness,
    build_domain_runtime_contract_witness,
    summarize_witnesses,
    witness_from_runtime_trace_row,
    witness_trace_fields_from_result,
    write_domain_runtime_contract_artifacts,
)
from .domain_validity import DomainValiditySemantics, domain_certificate_validity_semantics
from .kernel import (
    build_observation_consistent_state_set,
    build_observation_packet,
    build_reliability_assessment,
    build_repair_decision,
    build_safety_certificate,
    build_safety_spec,
    derive_safe_action_set,
    execute_universal_step,
)
from .no_free_safety import (
    CounterexampleResult,
    construct_counterexample,
    formal_principle_statement,
)
from .observation_ambiguity import (
    build_observation_ambiguity_contract_summary,
    common_safe_core,
    observation_only_bayes_lower_bound,
    verify_covered_orius_release,
)
from .risk_bounds import (
    FrontierPoint,
    assert_coverage_guarantee,
    calibration_contract_verify,
    compute_empirical_coverage,
    compute_episode_risk_bound,
    compute_frontier,
    compute_step_risk_bound,
    evaluate_empirical_core_bound,
    minimum_reliability_for_target,
    verify_inflation_geq_one,
)
from .theorem_discharge import (
    DischargeThresholds,
    compute_t9_discharge_from_csv,
    compute_t9_discharge_from_rows,
    compute_t10_discharge_from_csv,
    compute_t10_discharge_from_rows,
)

__all__ = [
    "AV_BRAKE_HOLD_CONTRACT_ID",
    "HEALTHCARE_FAIL_SAFE_CONTRACT_ID",
    "ContractVerifier",
    "ContractViolation",
    "CounterexampleResult",
    "DischargeThresholds",
    "DomainInstantiation",
    "DomainRuntimeContractWitness",
    "DomainValiditySemantics",
    "FrontierPoint",
    "ObservationConsistentStateSet",
    "ObservationPacket",
    "ReliabilityAssessment",
    "RepairDecision",
    "SafeActionSet",
    "SafetyCertificate",
    "SafetySpec",
    "UniversalStepResult",
    "assert_coverage_guarantee",
    "build_domain_runtime_contract_witness",
    "build_observation_ambiguity_contract_summary",
    "build_observation_consistent_state_set",
    "build_observation_packet",
    "build_reliability_assessment",
    "build_repair_decision",
    "build_safety_certificate",
    "build_safety_spec",
    "calibration_contract_verify",
    "common_safe_core",
    "compute_empirical_coverage",
    "compute_episode_risk_bound",
    "compute_frontier",
    "compute_step_risk_bound",
    "compute_t9_discharge_from_csv",
    "compute_t9_discharge_from_rows",
    "compute_t10_discharge_from_csv",
    "compute_t10_discharge_from_rows",
    "construct_counterexample",
    "derive_safe_action_set",
    "domain_certificate_validity_semantics",
    "evaluate_empirical_core_bound",
    "execute_universal_step",
    "formal_principle_statement",
    "minimum_reliability_for_target",
    "observation_only_bayes_lower_bound",
    "summarize_witnesses",
    "verify_covered_orius_release",
    "verify_inflation_geq_one",
    "witness_from_runtime_trace_row",
    "witness_trace_fields_from_result",
    "write_domain_runtime_contract_artifacts",
]
