"""ORIUS universal degraded-observation theory kernel."""
from .contracts import (
    ContractVerifier,
    ContractViolation,
    DomainInstantiation,
    ObservationConsistentStateSet,
    ObservationPacket,
    ReliabilityAssessment,
    RepairDecision,
    SafeActionSet,
    SafetyCertificate,
    SafetySpec,
    UniversalStepResult,
)
from .kernel import (
    build_observation_consistent_state_set,
    build_observation_packet,
    build_reliability_assessment,
    build_repair_decision,
    build_safety_certificate,
    build_safety_spec,
    derive_safe_action_set,
    execute_universal_step,
)
from .risk_bounds import (
    FrontierPoint,
    assert_coverage_guarantee,
    compute_empirical_coverage,
    compute_episode_risk_bound,
    compute_frontier,
    compute_step_risk_bound,
    evaluate_empirical_core_bound,
    minimum_reliability_for_target,
    verify_inflation_geq_one,
)

__all__ = [
    "ContractVerifier",
    "ContractViolation",
    "DomainInstantiation",
    "ObservationPacket",
    "ReliabilityAssessment",
    "ObservationConsistentStateSet",
    "SafetySpec",
    "SafeActionSet",
    "RepairDecision",
    "SafetyCertificate",
    "UniversalStepResult",
    "build_observation_packet",
    "build_reliability_assessment",
    "build_observation_consistent_state_set",
    "build_safety_spec",
    "derive_safe_action_set",
    "build_repair_decision",
    "build_safety_certificate",
    "execute_universal_step",
    "verify_inflation_geq_one",
    "compute_empirical_coverage",
    "assert_coverage_guarantee",
    "compute_step_risk_bound",
    "compute_episode_risk_bound",
    "evaluate_empirical_core_bound",
    "FrontierPoint",
    "compute_frontier",
    "minimum_reliability_for_target",
]
