#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd
import yaml


def repo_to_paper_rel(path: Path, repo_root: Path, paper_dir: Path) -> str:
    abs_path = (repo_root / path).resolve() if not path.is_absolute() else path.resolve()
    return str(abs_path.relative_to(paper_dir.resolve()))


def write_table_tex(token: str, csv_path: Path, title: str, out_path: Path) -> None:
    df = pd.read_csv(csv_path)
    tabular = df.to_latex(index=False, escape=True)
    content = (
        "\\begin{table}[htbp]\n"
        "\\centering\n"
        "\\small\n"
        f"\\caption{{{title}}}\n"
        f"\\label{{tab:{token}}}\n"
        f"{tabular}\n"
        "\\end{table}\n"
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate LaTeX table fragments and manifest lookup for paper assets")
    parser.add_argument("--manifest", default="paper/manifest.yaml")
    parser.add_argument("--paper-dir", default="paper")
    args = parser.parse_args()

    repo_root = Path.cwd()
    manifest_path = repo_root / args.manifest
    paper_dir = repo_root / args.paper_dir

    if not manifest_path.exists():
        print(f"ERROR: manifest not found: {manifest_path}", file=sys.stderr)
        return 1

    with manifest_path.open("r", encoding="utf-8") as f:
        manifest = yaml.safe_load(f) or {}

    figures = manifest.get("figures") or {}
    tables = manifest.get("tables") or {}

    lookup_lines = ["% Auto-generated by scripts/build_paper_table_tex.py"]

    for token, entry in figures.items():
        fig_path = Path(entry["path"])
        rel = repo_to_paper_rel(fig_path, repo_root, paper_dir)
        lookup_lines.append(f"\\DeclarePaperFigure{{{token}}}{{{rel}}}")

    generated_dir = paper_dir / "assets/tables/generated"
    for token, entry in tables.items():
        csv_path = repo_root / entry["path"]
        if not csv_path.exists():
            print(f"ERROR: table csv missing for {token}: {csv_path}", file=sys.stderr)
            return 1
        title = entry.get("title", token)
        out_tex = generated_dir / f"{csv_path.stem}.tex"
        write_table_tex(token, csv_path, title, out_tex)
        rel = repo_to_paper_rel(out_tex, repo_root, paper_dir)
        lookup_lines.append(f"\\DeclarePaperTable{{{token}}}{{{rel}}}")

    lookup_path = paper_dir / "assets/data/manifest_lookup.tex"
    lookup_path.parent.mkdir(parents=True, exist_ok=True)
    lookup_path.write_text("\n".join(lookup_lines) + "\n", encoding="utf-8")

    print(f"Wrote table fragments under {generated_dir}")
    print(f"Wrote lookup map: {lookup_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
