#!/usr/bin/env python3
"""Generate a LaTeX appendix block from the publication release manifest."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = REPO_ROOT / "reports" / "publication" / "release_manifest.json"
DEFAULT_OUT = REPO_ROOT / "reports" / "publication" / "reproducibility_appendix_generated.tex"


def _latex_escape(value: object) -> str:
    text = str(value)
    for src, dst in (
        ("\\", "\\textbackslash{}"),
        ("_", "\\_"),
        ("&", "\\&"),
        ("%", "\\%"),
        ("#", "\\#"),
        ("{", "\\{"),
        ("}", "\\}"),
    ):
        text = text.replace(src, dst)
    return text


def _build_tex(manifest: dict[str, object], manifest_rel: str) -> str:
    release_id = manifest.get("release_id", "unknown")
    source_runs = manifest.get("source_runs", {}) if isinstance(manifest.get("source_runs"), dict) else {}
    paper_policy = manifest.get("paper_metric_policy", {}) if isinstance(manifest.get("paper_metric_policy"), dict) else {}
    artifact_hashes = manifest.get("artifact_hashes_sha256", {}) if isinstance(manifest.get("artifact_hashes_sha256"), dict) else {}
    lines = [
        "% Auto-generated by scripts/generate_reproducibility_appendix.py",
        "\\section{Release Manifest Summary}",
        f"The active reproducibility root is \\path{{{manifest_rel}}}.",
        "\\begin{itemize}",
        f"  \\item Release ID: \\texttt{{{_latex_escape(release_id)}}}",
        f"  \\item Master manuscript: \\path{{{_latex_escape(paper_policy.get('master_manuscript', 'paper/paper.tex'))}}}",
        f"  \\item Source run families captured: {len(source_runs)}",
        f"  \\item Hashed publication artifacts: {len(artifact_hashes)}",
        "\\end{itemize}",
        "",
        "\\section{Source Runs}",
        "\\begin{longtable}{p{2.0cm}p{2.0cm}p{7.5cm}}",
        "\\toprule",
        "\\textbf{Dataset} & \\textbf{Run ID} & \\textbf{Manifest path}\\\\",
        "\\midrule",
        "\\endhead",
    ]
    for dataset, payload in sorted(source_runs.items()):
        run_id = payload.get("run_id", "n/a") if isinstance(payload, dict) else "n/a"
        manifest_path = payload.get("manifest_path", "n/a") if isinstance(payload, dict) else "n/a"
        lines.append(
            f"{_latex_escape(dataset)} & \\texttt{{{_latex_escape(run_id)}}} & \\path{{{_latex_escape(manifest_path)}}}\\\\"
        )
    lines.extend(
        [
            "\\bottomrule",
            "\\end{longtable}",
            "",
            "\\section{Tracked Publication Artifacts}",
            "\\begin{longtable}{p{8.0cm}p{6.0cm}}",
            "\\toprule",
            "\\textbf{Artifact} & \\textbf{SHA-256}\\\\",
            "\\midrule",
            "\\endhead",
        ]
    )
    for artifact, sha in sorted(artifact_hashes.items()):
        lines.append(f"\\path{{{_latex_escape(artifact)}}} & \\texttt{{{_latex_escape(sha)}}}\\\\")
    lines.extend(["\\bottomrule", "\\end{longtable}", ""])
    return "\n".join(lines)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate reproducibility appendix TeX from release manifest")
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST, help="Release manifest path")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="Output TeX path")
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    manifest_path = args.manifest.resolve()
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest_rel = str(manifest_path.relative_to(REPO_ROOT))
    tex = _build_tex(manifest, manifest_rel)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(tex + "\n", encoding="utf-8")
    print(f"wrote {args.out.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
