#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


def flatten(obj: Any, prefix: str = "") -> dict[str, Any]:
    out: dict[str, Any] = {}
    if isinstance(obj, dict):
        for k, v in obj.items():
            key = f"{prefix}_{k}" if prefix else str(k)
            out.update(flatten(v, key))
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            key = f"{prefix}_{i}" if prefix else str(i)
            out.update(flatten(v, key))
    else:
        out[prefix] = obj
    return out


def normalize_key(key: str) -> str:
    return re.sub(r"[^A-Z0-9]+", "_", key.upper()).strip("_")


def tex_escape(value: str) -> str:
    return (
        value.replace("\\", r"\\")
        .replace("_", r"\_")
        .replace("%", r"\%")
        .replace("&", r"\&")
        .replace("#", r"\#")
    )


def format_value(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        rendered = f"{value:.6f}".rstrip("0").rstrip(".")
        return rendered if rendered else "0"
    return str(value)


def collect_metric_defaults(tex: str) -> dict[str, str]:
    # \PaperMetric{KEY}{DEFAULT}
    pairs = re.findall(r"\\PaperMetric\{([^}]+)\}\{([^}]*)\}", tex)
    return dict(pairs)


def main() -> int:
    parser = argparse.ArgumentParser(description="Update LaTeX PaperMetric values from stats summary JSON")
    parser.add_argument("--paper", default="paper/paper.tex")
    parser.add_argument("--stats", default="reports/publication/stats_summary.json")
    parser.add_argument("--out", default="paper/assets/data/metrics_values.tex")
    args = parser.parse_args()

    paper_path = Path(args.paper)
    stats_path = Path(args.stats)
    out_path = Path(args.out)

    if not paper_path.exists():
        raise SystemExit(f"paper file not found: {paper_path}")
    if not stats_path.exists():
        raise SystemExit(f"stats file not found: {stats_path}")

    paper_text = paper_path.read_text(encoding="utf-8")
    metric_defaults = collect_metric_defaults(paper_text)

    stats = json.loads(stats_path.read_text(encoding="utf-8"))
    flat_stats = flatten(stats)
    normalized_map = {normalize_key(k): v for k, v in flat_stats.items() if k}

    lines = ["% Auto-generated by scripts/update_paper_metrics.py"]

    for key, default in sorted(metric_defaults.items()):
        value = normalized_map.get(normalize_key(key), default)
        rendered = tex_escape(format_value(value))
        lines.append(rf"\expandafter\def\csname PaperMetric@{key}\endcsname{{{rendered}}}")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path} with {len(metric_defaults)} metric keys")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
